name: Security Secrets Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  trufflehog:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper diff

      - name: Check if this is a valid scan scenario
        id: check_scan
        run: |
          # Get current commit and parent
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PARENT_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")

          echo "Current commit: $CURRENT_COMMIT"
          echo "Parent commit: $PARENT_COMMIT"

          # Check if we have a parent commit (not initial commit)
          if [ -z "$PARENT_COMMIT" ] || [ "$CURRENT_COMMIT" = "$PARENT_COMMIT" ]; then
            echo "scan_mode=full" >> $GITHUB_OUTPUT
            echo "This appears to be an initial commit or single commit - will scan full repo"
          else
            echo "scan_mode=diff" >> $GITHUB_OUTPUT
            echo "Normal commit - will scan diff"
          fi

      - name: Run TruffleHog (Full Repository Scan)
        if: steps.check_scan.outputs.scan_mode == 'full'
        uses: trufflesecurity/trufflehog@main
        with:
          # Scan the entire repository for initial commits
          path: ./
          base: ""
          head: ""
          extra_args: --debug --only-verified

      - name: Run TruffleHog (Diff Scan)
        if: steps.check_scan.outputs.scan_mode == 'diff'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Report scan completion
        run: |
          echo "✅ TruffleHog secrets scan completed successfully"
          echo "Scan mode used: ${{ steps.check_scan.outputs.scan_mode }}"